// <auto-generated />
namespace KE.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modQuote2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modQuote2));
        
        string IMigrationMetadata.Id
        {
            get { return "201601241536201_modQuote2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
