//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KExpert.ApiServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/KExpert.Ws.ExceptionHandler")]
    [System.SerializableAttribute()]
    public partial class ExceptionFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://karexpert.hu/kews/", ConfigurationName="ApiServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IService/GetServertime", ReplyAction="http://karexpert.hu/kews/IService/GetServertimeResponse")]
        string GetServertime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IService/GetServertime", ReplyAction="http://karexpert.hu/kews/IService/GetServertimeResponse")]
        System.Threading.Tasks.Task<string> GetServertimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IService/GetQuotation", ReplyAction="http://karexpert.hu/kews/IService/GetQuotationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KExpert.ApiServiceReference.ExceptionFaultContract), Action="http://karexpert.hu/kews/IService/GetQuotationExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/KExpert.Ws.ExceptionHandler")]
        KE.Entities.WsModels.PolicyQuoteResponse GetQuotation(KE.Entities.WsModels.PolicyQuoteRequest inputParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IService/GetQuotation", ReplyAction="http://karexpert.hu/kews/IService/GetQuotationResponse")]
        System.Threading.Tasks.Task<KE.Entities.WsModels.PolicyQuoteResponse> GetQuotationAsync(KE.Entities.WsModels.PolicyQuoteRequest inputParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IService/GetQuote", ReplyAction="http://karexpert.hu/kews/IService/GetQuoteResponse")]
        KE.Entities.WsModels.PolicyQuoteResponse GetQuote(KE.Entities.WsModels.PolicyQuoteRequest inputParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IService/GetQuote", ReplyAction="http://karexpert.hu/kews/IService/GetQuoteResponse")]
        System.Threading.Tasks.Task<KE.Entities.WsModels.PolicyQuoteResponse> GetQuoteAsync(KE.Entities.WsModels.PolicyQuoteRequest inputParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IService/CreatePolicy", ReplyAction="http://karexpert.hu/kews/IService/CreatePolicyResponse")]
        KE.Entities.WsModels.CreatePolicyResponse CreatePolicy(KE.Entities.WsModels.CreatePolicyRequest inputParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IService/CreatePolicy", ReplyAction="http://karexpert.hu/kews/IService/CreatePolicyResponse")]
        System.Threading.Tasks.Task<KE.Entities.WsModels.CreatePolicyResponse> CreatePolicyAsync(KE.Entities.WsModels.CreatePolicyRequest inputParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : KExpert.ApiServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<KExpert.ApiServiceReference.IService>, KExpert.ApiServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetServertime() {
            return base.Channel.GetServertime();
        }
        
        public System.Threading.Tasks.Task<string> GetServertimeAsync() {
            return base.Channel.GetServertimeAsync();
        }
        
        public KE.Entities.WsModels.PolicyQuoteResponse GetQuotation(KE.Entities.WsModels.PolicyQuoteRequest inputParameters) {
            return base.Channel.GetQuotation(inputParameters);
        }
        
        public System.Threading.Tasks.Task<KE.Entities.WsModels.PolicyQuoteResponse> GetQuotationAsync(KE.Entities.WsModels.PolicyQuoteRequest inputParameters) {
            return base.Channel.GetQuotationAsync(inputParameters);
        }
        
        public KE.Entities.WsModels.PolicyQuoteResponse GetQuote(KE.Entities.WsModels.PolicyQuoteRequest inputParameters) {
            return base.Channel.GetQuote(inputParameters);
        }
        
        public System.Threading.Tasks.Task<KE.Entities.WsModels.PolicyQuoteResponse> GetQuoteAsync(KE.Entities.WsModels.PolicyQuoteRequest inputParameters) {
            return base.Channel.GetQuoteAsync(inputParameters);
        }
        
        public KE.Entities.WsModels.CreatePolicyResponse CreatePolicy(KE.Entities.WsModels.CreatePolicyRequest inputParameters) {
            return base.Channel.CreatePolicy(inputParameters);
        }
        
        public System.Threading.Tasks.Task<KE.Entities.WsModels.CreatePolicyResponse> CreatePolicyAsync(KE.Entities.WsModels.CreatePolicyRequest inputParameters) {
            return base.Channel.CreatePolicyAsync(inputParameters);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://karexpert.hu/kews/", ConfigurationName="ApiServiceReference.IMobileService")]
    public interface IMobileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/GetPolicyDetails", ReplyAction="http://karexpert.hu/kews/IMobileService/GetPolicyDetailsResponse")]
        KE.Entities.WsMobile.PolicyDetails GetPolicyDetails(string policyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/GetPolicyDetails", ReplyAction="http://karexpert.hu/kews/IMobileService/GetPolicyDetailsResponse")]
        System.Threading.Tasks.Task<KE.Entities.WsMobile.PolicyDetails> GetPolicyDetailsAsync(string policyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/SaveClaimDocuments", ReplyAction="http://karexpert.hu/kews/IMobileService/SaveClaimDocumentsResponse")]
        bool SaveClaimDocuments(string policyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/SaveClaimDocuments", ReplyAction="http://karexpert.hu/kews/IMobileService/SaveClaimDocumentsResponse")]
        System.Threading.Tasks.Task<bool> SaveClaimDocumentsAsync(string policyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/GetImageThumbnails", ReplyAction="http://karexpert.hu/kews/IMobileService/GetImageThumbnailsResponse")]
        KE.Entities.WsMobile.ImageSetCollection GetImageThumbnails(string policyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/GetImageThumbnails", ReplyAction="http://karexpert.hu/kews/IMobileService/GetImageThumbnailsResponse")]
        System.Threading.Tasks.Task<KE.Entities.WsMobile.ImageSetCollection> GetImageThumbnailsAsync(string policyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/GetFullImage", ReplyAction="http://karexpert.hu/kews/IMobileService/GetFullImageResponse")]
        KE.Entities.WsMobile.Image GetFullImage(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/GetFullImage", ReplyAction="http://karexpert.hu/kews/IMobileService/GetFullImageResponse")]
        System.Threading.Tasks.Task<KE.Entities.WsMobile.Image> GetFullImageAsync(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/UploadImageSets", ReplyAction="http://karexpert.hu/kews/IMobileService/UploadImageSetsResponse")]
        bool UploadImageSets(KE.Entities.WsMobile.ImageSetCollection imageSetCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/UploadImageSets", ReplyAction="http://karexpert.hu/kews/IMobileService/UploadImageSetsResponse")]
        System.Threading.Tasks.Task<bool> UploadImageSetsAsync(KE.Entities.WsMobile.ImageSetCollection imageSetCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/PostBase64", ReplyAction="http://karexpert.hu/kews/IMobileService/PostBase64Response")]
        string PostBase64(string base64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/PostBase64", ReplyAction="http://karexpert.hu/kews/IMobileService/PostBase64Response")]
        System.Threading.Tasks.Task<string> PostBase64Async(string base64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/GetBase64", ReplyAction="http://karexpert.hu/kews/IMobileService/GetBase64Response")]
        string GetBase64(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://karexpert.hu/kews/IMobileService/GetBase64", ReplyAction="http://karexpert.hu/kews/IMobileService/GetBase64Response")]
        System.Threading.Tasks.Task<string> GetBase64Async(string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMobileServiceChannel : KExpert.ApiServiceReference.IMobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileServiceClient : System.ServiceModel.ClientBase<KExpert.ApiServiceReference.IMobileService>, KExpert.ApiServiceReference.IMobileService {
        
        public MobileServiceClient() {
        }
        
        public MobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KE.Entities.WsMobile.PolicyDetails GetPolicyDetails(string policyId) {
            return base.Channel.GetPolicyDetails(policyId);
        }
        
        public System.Threading.Tasks.Task<KE.Entities.WsMobile.PolicyDetails> GetPolicyDetailsAsync(string policyId) {
            return base.Channel.GetPolicyDetailsAsync(policyId);
        }
        
        public bool SaveClaimDocuments(string policyId) {
            return base.Channel.SaveClaimDocuments(policyId);
        }
        
        public System.Threading.Tasks.Task<bool> SaveClaimDocumentsAsync(string policyId) {
            return base.Channel.SaveClaimDocumentsAsync(policyId);
        }
        
        public KE.Entities.WsMobile.ImageSetCollection GetImageThumbnails(string policyId) {
            return base.Channel.GetImageThumbnails(policyId);
        }
        
        public System.Threading.Tasks.Task<KE.Entities.WsMobile.ImageSetCollection> GetImageThumbnailsAsync(string policyId) {
            return base.Channel.GetImageThumbnailsAsync(policyId);
        }
        
        public KE.Entities.WsMobile.Image GetFullImage(string guid) {
            return base.Channel.GetFullImage(guid);
        }
        
        public System.Threading.Tasks.Task<KE.Entities.WsMobile.Image> GetFullImageAsync(string guid) {
            return base.Channel.GetFullImageAsync(guid);
        }
        
        public bool UploadImageSets(KE.Entities.WsMobile.ImageSetCollection imageSetCollection) {
            return base.Channel.UploadImageSets(imageSetCollection);
        }
        
        public System.Threading.Tasks.Task<bool> UploadImageSetsAsync(KE.Entities.WsMobile.ImageSetCollection imageSetCollection) {
            return base.Channel.UploadImageSetsAsync(imageSetCollection);
        }
        
        public string PostBase64(string base64) {
            return base.Channel.PostBase64(base64);
        }
        
        public System.Threading.Tasks.Task<string> PostBase64Async(string base64) {
            return base.Channel.PostBase64Async(base64);
        }
        
        public string GetBase64(string guid) {
            return base.Channel.GetBase64(guid);
        }
        
        public System.Threading.Tasks.Task<string> GetBase64Async(string guid) {
            return base.Channel.GetBase64Async(guid);
        }
    }
}
